name: Build libzstd
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/sodium.yml'
      - '.github/scripts/package-sodium.sh'

permissions:
  contents: write

jobs:
  build:
    name: Build zstd for ${{ matrix.config.rid }}
    runs-on: ${{ matrix.config.os }}
    outputs:
      version: ${{ steps.build.outputs.version }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: windows-latest,
              command: "make libzstd ZSTD_LIB_DEPRECATED=0 ZSTD_LEGACY_SUPPORT=0",
              output-file: "dll\\libzstd.dll",
              file: "libzstd.dll",
              rid: "win-x64",
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Build ${{ matrix.config.file }}"
        id: build
        shell: bash
        run: |
          export WORKSPACE='${{ github.workspace }}'
          export COMMAND='${{ matrix.config.command }}'
          export OUTPUT_FILE='${{ matrix.config.output-file }}'
          export FILE='${{ matrix.config.file }}'
          export RID='${{ matrix.config.rid }}'
          export JOB_INDEX='${{ strategy.job-index }}'
          export GITHUB_RUN_NUMBER='${{ github.run_number }}'
          bash '${{ github.workspace }}/.github/scripts/package-libzstd.sh'
      - name: "Update ${{ matrix.config.rid }}"
        uses: EndBug/add-and-commit@v9
        with:
          add: "libs/libzstd/"
          default_author: github_actions
          message: Update libzstd ${{ matrix.config.rid }} to ${{ steps.build.outputs.version }}
          pull: "--rebase --autostash"
          push: true
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: libzstd-${{ steps.build.outputs.version }}-${{ matrix.config.rid }}
          path: libs/libzstd/${{ matrix.config.rid }}/native/${{ matrix.config.file }}
  update-version:
    name: Update .NET project version
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.outputs.version != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update version
        run: |
          sed -i "s|<Version>.*</Version>|<Version>${{ needs.build.outputs.version }}</Version>|g" "${{ github.workspace }}/src/DSharpPlus.Natives.Zstd/DSharpPlus.Natives.Zstd.csproj"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Push changes"
        uses: EndBug/add-and-commit@v9
        with:
          add: "src/DSharpPlus.Natives.Zstd/DSharpPlus.Natives.Zstd.csproj"
          default_author: github_actions
          message: Update Sodium version to ${{ needs.build.outputs.version }}
          pull: "--rebase --autostash"
          push: true