name: Build zstd
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/zstd.yml'

env:
  COMMON_CMAKE_FLAGS: "-DZSTD_MULTITHREAD_SUPPORT=ON -DZSTD_LEGACY_SUPPORT=OFF -DZSTD_BUILD_PROGRAMS=OFF -DZSTD_BUILD_STATIC=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release"

jobs:
  build:
    name: Build zstd
    runs-on: ${{ matrix.os }}

    outputs:
      version: ${{ steps.print-version.outputs.version }}

    strategy:
      fail-fast: false # Run the other two OSs even if one fails
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
          
    steps:
      - name: Clone zstd repo
        uses: actions/checkout@v4.2.2
        with:
          repository: facebook/zstd
          submodules: recursive

      - name: Checkout latest Tag
        shell: bash
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag | grep -E ^v[0-9]+.[0-9]+.[0-9]+$ | tail -1)
          git checkout "$LATEST_TAG"
          echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Build zstd
        shell: bash
        run: |
          cd build/cmake
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            for arch in x64 ARM64; do # We dont want Win32
              mkdir -p ../../output/$arch
              mkdir build-$arch
              cd build-$arch
              cmake $COMMON_CMAKE_FLAGS -A $arch ..
              cmake --build . -j 4 --config Release
              cp lib/Release/zstd.dll ../../../output/$arch/libzstd.dll
              cd ..
            done
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            for arch in x64 ARM64; do
              mkdir -p ../../output/$arch
              mkdir build-$arch
              cd build-$arch
              if [[ "$arch" == "ARM64" ]]; then
                sudo apt update
                sudo apt install cmake gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
                cmake $COMMON_CMAKE_FLAGS -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ ..
              else
                cmake $COMMON_CMAKE_FLAGS ..
              fi
              cmake --build . -j 4
              cp lib/libzstd.so ../../../output/$arch/libzstd.so
              cd ..
            done
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mkdir build ../../output
            cd build
            cmake $COMMON_CMAKE_FLAGS "-DCMAKE_OSX_ARCHITECTURES=arm64;arm64e;x86_64;x86_64h" ..
            cmake --build . -j 4 --config Release
            cp lib/libzstd.dylib ../../../output/libzstd.dylib
            cd ..
          fi

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: zstd-${{ matrix.os }}
          path: output
          compression-level: 9 # Prefer smaller downloads over a shorter workflow runtime

  build-musl:
    name: Build zstd (alpine-musl)
    runs-on: ubuntu-latest
    
    # We sadly cant use a matrix to run x64 and ARM64, because it would give use 2 artifacts
    steps:
      - name: Clone zstd repo
        uses: actions/checkout@v4.2.2
        with:
          repository: facebook/zstd
          submodules: recursive

      - name: Checkout latest Tag
        shell: bash
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag | grep -E ^v[0-9]+.[0-9]+.[0-9]+$ | tail -1)
          git checkout "$LATEST_TAG"

      - name: Setup Alpine Linux for x64
        uses: jirutka/setup-alpine@v1
        with:
          packages: >
            build-base
            cmake
            git
            make
            gcc
            g++

      - name: Build zstd for x64 (musl)
        shell: alpine.sh {0}
        run: |
          cd build/cmake
          mkdir -p ../../output/x64
          mkdir -p build-x64
          cd build-x64
          cmake $COMMON_CMAKE_FLAGS ..
          cmake --build . -j 4
          cp lib/libzstd.so ../../../output/x64/libzstd.musl.so
          cd ..
      
      - name: Setup Alpine Linux for ARM64
        uses: jirutka/setup-alpine@v1
        with:
          arch: aarch64
          packages: >
            build-base
            cmake
            git
            make
            gcc
            g++
  
      - name: Build zstd for ARM64 (musl)
        shell: alpine.sh {0}
        run: |
          cd build/cmake
          mkdir -p ../../output/ARM64
          mkdir -p build-ARM64
          cd build-ARM64
          cmake $COMMON_CMAKE_FLAGS ..
          cmake --build . -j 4
          cp lib/libzstd.so ../../../output/ARM64/libzstd.musl.so
          cd ..

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: zstd-alpine-latest
          path: output
          compression-level: 9 # Prefer smaller downloads over a shorter workflow runtime

  publish-nuget:
    needs: [build, build-musl]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout CSPROJ files
        uses: actions/checkout@v4.2.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: temp
          pattern: zstd-*
          merge-multiple: true

      - name: Move Artifacts
        run: |
          mkdir -p lib/zstd/win-x64/native
          mkdir -p lib/zstd/linux-x64/native
          mkdir -p lib/zstd/win-arm64/native
          mkdir -p lib/zstd/linux-arm64/native
          mkdir -p lib/zstd/osx/native
          mkdir -p lib/zstd/linux-musl-x64/native
          mkdir -p lib/zstd/linux-musl-arm64/native
          cp temp/x64/libzstd.dll lib/zstd/win-x64/native/libzstd.dll
          cp temp/x64/libzstd.so lib/zstd/linux-x64/native/libzstd.so
          cp temp/ARM64/libzstd.dll lib/zstd/win-arm64/native/libzstd.dll
          cp temp/ARM64/libzstd.so lib/zstd/linux-arm64/native/libzstd.so
          cp temp/libzstd.dylib lib/zstd/osx/native/libzstd.dylib
          cp temp/x64/libzstd.musl.so lib/zstd/linux-musl-x64/native/libzstd.so
          cp temp/ARM64/libzstd.musl.so lib/zstd/linux-musl-arm64/native/libzstd.so

      - name: Pack DSharpPlus.Natives.Zstd
        shell: bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          VERSION: ${{ needs.build.outputs.version }}
        run: |
          VERSION="${VERSION:1}"
          dotnet pack ./build/DSharpPlus.Natives.Zstd.csproj -c Release -p:Version="$VERSION.${{ github.run_number }}"
          dotnet nuget push "artifacts/**" --skip-duplicate -k "$NUGET_API_KEY" -s https://api.nuget.org/v3/index.json