name: Build zstd
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/zstd.yml'

jobs:
  build:
    name: Build zstd
    runs-on: ${{ matrix.os }}

    outputs:
      version: ${{ steps.print-version.outputs.version }}

    strategy:
      fail-fast: false # Run the other two OSs even if one fails
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
          
    steps:
      - name: Clone zstd repo
        uses: actions/checkout@v4.2.2
        with:
          repository: facebook/zstd
          submodules: recursive

      # Disabled because 1.5.6 has an issue with MSVC which has not yet been fixed in a newer Tag, see https://github.com/facebook/zstd/pull/4019
      #- name: Checkout latest Tag
      #  shell: bash
      #  run: git fetch --tags && git checkout "$(git describe --tags "$(git rev-list --tags --max-count=1)")"
      
      # we do need the version though
      - name: Print Version
        id: print-version
        shell: bash
        run: |
          git fetch --tags 
          version=$(git describe --tags $(git rev-list --tags --max-count=1)) >> $GITHUB_OUTPUT
      
      - name: Build zstd
        shell: bash
        run: |
          cd build/cmake
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            for arch in x64 ARM64; do # We dont want Win32
              mkdir -p ../../output/$arch
              mkdir build-$arch
              cd build-$arch
              cmake -DZSTD_MULTITHREAD_SUPPORT=ON -DZSTD_LEGACY_SUPPORT=OFF -DZSTD_BUILD_PROGRAMS=OFF -DZSTD_BUILD_STATIC=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -A $arch ..
              cmake --build . -j 4 --config Release
              cp lib/Release/zstd.dll ../../../output/$arch/libzstd.dll
              cd ..
            done
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            for arch in x64 ARM64; do
              mkdir -p ../../output/$arch
              mkdir build-$arch
              cd build-$arch
              if [[ "$arch" == "ARM64" ]]; then
                sudo apt update
                sudo apt install cmake gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
                cmake -DZSTD_MULTITHREAD_SUPPORT=ON -DZSTD_LEGACY_SUPPORT=OFF -DZSTD_BUILD_PROGRAMS=OFF -DZSTD_BUILD_STATIC=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ -DCMAKE_BUILD_TYPE=Release ..
              else
                cmake -DZSTD_MULTITHREAD_SUPPORT=ON -DZSTD_LEGACY_SUPPORT=OFF -DZSTD_BUILD_PROGRAMS=OFF -DZSTD_BUILD_STATIC=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
              fi
              cmake --build . -j 4
              cp lib/libzstd.so ../../../output/$arch/libzstd.so
              cd ..
            done
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mkdir build ../../output
            cd build
            cmake -DZSTD_MULTITHREAD_SUPPORT=ON -DZSTD_LEGACY_SUPPORT=OFF -DZSTD_BUILD_PROGRAMS=OFF -DZSTD_BUILD_STATIC=OFF -DBUILD_SHARED_LIBS=ON "-DCMAKE_OSX_ARCHITECTURES=arm64;arm64e;x86_64;x86_64h" -DCMAKE_BUILD_TYPE=Release ..
            cmake --build . -j 4 --config Release
            cp lib/libzstd.dylib ../../../output/libzstd.dylib
            cd ..
          fi

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: zstd-${{ matrix.os }}
          path: output
          compression-level: 9 # Prefer smaller downloads over a shorter workflow runtime

  publish-nuget:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CSPROJ files
        uses: actions/checkout@v4.2.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: temp
          pattern: zstd-*
          merge-multiple: true

      - name: Move Artifacts
        run: |
          mkdir -p lib/zstd/win-x64/native
          mkdir -p lib/zstd/linux-x64/native
          mkdir -p lib/zstd/win-arm64/native
          mkdir -p lib/zstd/linux-arm64/native
          mkdir -p lib/zstd/osx/native
          cp temp/x64/libzstd.dll lib/zstd/win-x64/native/libzstd.dll
          cp temp/x64/libzstd.so lib/zstd/linux-x64/native/libzstd.so
          cp temp/ARM64/libzstd.dll lib/zstd/win-arm64/native/libzstd.dll
          cp temp/ARM64/libzstd.so lib/zstd/linux-arm64/native/libzstd.so
          cp temp/libzstd.dylib lib/zstd/osx/native/libzstd.dylib

      - name: Pack DSharpPlus.Natives.Zstd
        shell: bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          VERSION=${{ needs.build.outputs.version }}
          VERSION="${VERSION:1}"
          dotnet pack ./build/DSharpPlus.Natives.Zstd.csproj -c Release -p:Version="$(VERSION).${{ github.run_number }}"
          dotnet nuget push "artifacts/*" --skip-duplicate -k "$NUGET_API_KEY" -s https://api.nuget.org/v3/index.json